# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('decription', models.TextField()),
                ('image_link', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('year', models.CharField(default='', max_length=200)),
                ('isbn', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(default=0)),
                ('comments', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YABLAPP.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsbh', models.FloatField(default=0)),
                ('roman', models.IntegerField(default=0)),
                ('pos', models.IntegerField(default=0)),
                ('real', models.IntegerField(default=0)),
                ('span', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('grading', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='YABLAPP.Grading')),
                ('read_books', models.ManyToManyField(related_name='_reader_read_books_+', to='YABLAPP.Book')),
                ('tbr_books', models.ManyToManyField(related_name='_reader_tbr_books_+', to='YABLAPP.Book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookrating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YABLAPP.Reader'),
        ),
        migrations.AddField(
            model_name='book',
            name='grading',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='YABLAPP.Grading'),
        ),
    ]
