# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YABLAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
