# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YABLAPP', '0002_book_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grading',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reader',
            name='favourites',
            field=models.ManyToManyField(related_name='_reader_favourites_+', to='YABLAPP.Book'),
        ),
        migrations.AddField(
            model_name='reader',
            name='graded_books',
            field=models.ManyToManyField(related_name='_reader_graded_books_+', to='YABLAPP.Book'),
        ),
    ]
