# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YABLAPP', '0004_auto_20170108_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='decription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='favourites',
        ),
        migrations.AlterField(
            model_name='reader',
            name='grading',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='YABLAPP.Grading'),
            preserve_default=False,
        ),
    ]
